version: '3.8'
services:
  gateway:
    build:
      context: gateway
      dockerfile: ../gateway.Dockerfile
    image: shareit-gateway-image
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on: server, db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
      context: server
      dockerfile: ../server.Dockerfile
    image: shareit-server-image
    container_name: shareit_server
    ports:
      - "9090:9090"
    depends_on: db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - DB_NAME = shareit
      - POSTGRES_USER=mariia
      - POSTGRES_PASSWORD=password

  db:
    image: postgres:13.7-alpine
    container_name: shareit_db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=mariia
      - POSTGRES_PASSWORD=password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user